module.exports = [
  "3D Shooter",
  "Action",
  "Action RPG",
  "Adventure",
  "Baseball",
  "Basketball",
  "Beat'em Up",
  "Billiards",
  "Bowling",
  "Boxing",
  "Cabal Shooter",
  "Cinematic Platformer",
  "Compilation",
  "Cricket",
  "Educational",
  "Fighting",
  "First-Person Shooter",
  "Fishing",
  "Flight Simulator",
  "Football",
  "Gambling",
  "Game Show",
  "Golf",
  "Hockey",
  "Light Gun Shooter",
  "Pinball",
  "Platformer",
  "Puzzle",
  "Racing",
  "Rail Shooter",
  "Real-Time Strategy",
  "Real-Time Tactics",
  "RPG",
  "Rugby",
  "Run and Gun",
  "Scrolling Shooter",
  "Shoot'em Up",
  "Simulation",
  "Skateboarding",
  "Snowboarding",
  "Soccer",
  "Sports",
  "Strategy",
  "Tabletop",
  "Tennis",
  "Vehicular Combat",
  "Volleyball",
  "Wrestling",
]
